/**
 * @file Version.h
 * @brief Version information for BME280.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef BME280_VERSION_STRING
#define BME280_VERSION_STRING "1.3.0"
#endif

#ifndef BME280_BUILD_DATE
#define BME280_BUILD_DATE __DATE__
#endif

#ifndef BME280_BUILD_TIME
#define BME280_BUILD_TIME __TIME__
#endif

#ifndef BME280_BUILD_TIMESTAMP
#define BME280_BUILD_TIMESTAMP BME280_BUILD_DATE " " BME280_BUILD_TIME
#endif

#ifndef BME280_GIT_COMMIT
#define BME280_GIT_COMMIT "unknown"
#endif

#ifndef BME280_GIT_STATUS
#define BME280_GIT_STATUS "unknown"
#endif

#ifndef BME280_VERSION_FULL
#define BME280_VERSION_FULL BME280_VERSION_STRING " (" BME280_GIT_COMMIT ", " BME280_BUILD_TIMESTAMP ", " BME280_GIT_STATUS ")"
#endif

namespace BME280 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 3;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = BME280_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10300;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10300;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = BME280_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = BME280_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = BME280_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = BME280_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = BME280_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = BME280_VERSION_FULL;

}  // namespace BME280
